ureca-final/pov-backend

.github/workflows/cicd.yml
scripts/deploy.sh
src/main/resources/application.yml

feat: cicd 구성, RDS 연결 설정

---

.github/workflows/cicd.yml

feat: 경로 수정

---

.github/workflows/cicd.yml

feat: cicd 트리거 조건 수정 main -> dev

---

src/main/resources/application.yml

refactor: username, password 환경변수 키값 변경

---

.github/workflows/cicd.yml

feat: 환경변수 출력

---

.github/workflows/cicd.yml

feat: 트리거 조건 변경

---

build.gradle
src/test/resources/application.yml

feat: h2 의존성 추가

---

.github/workflows/cicd.yml

feat: cicd.yml jar 자동감지 기능 작성

---

build.gradle

feat: actuator 활성화

---

.github/workflows/cicd.yml

feat: cicd.yml 수정

---

.github/workflows/cicd.yml

feat: 인스턴스 배포 코드 수정

---

.github/workflows/cicd.yml

feat: ssh키 생성로직 추가

---

build.gradle
src/main/java/net/pointofviews/common/domain/SoftDeleteEntity.java
src/main/java/net/pointofviews/member/domain/Member.java
src/main/java/net/pointofviews/notice/domain/Notice.java
src/main/java/net/pointofviews/notice/domain/NoticeReceive.java
src/main/java/net/pointofviews/notice/domain/NoticeSend.java
src/main/java/net/pointofviews/notice/domain/NoticeType.java
src/main/java/net/pointofviews/payment/domain/Payment.java
src/main/java/net/pointofviews/payment/domain/PaymentStatus.java
src/main/java/net/pointofviews/payment/domain/PaymentTransaction.java
src/main/java/net/pointofviews/payment/domain/PaymentType.java
src/main/java/net/pointofviews/premiere/domain/PaymentDomain.java
src/main/java/net/pointofviews/review/domain/Review.java
src/main/resources/application.yml
src/main/resources/db/migration/V1__init.sql

- 11.21 기준 erd를 entity에 반영
- V1__init.sql 추가
- flyway build.gradle, application.yml 추가

feat: V1 flyway db 생성

---

build.gradle
src/main/java/net/pointofviews/common/domain/BaseEntity.java
src/main/java/net/pointofviews/common/domain/SoftDeleteEntity.java
src/main/java/net/pointofviews/member/domain/Member.java
src/main/java/net/pointofviews/member/domain/MemberFavorGenre.java
src/main/resources/application.yml
src/test/java/net/pointofviews/member/domain/MemberFavorGenreTest.java
src/test/java/net/pointofviews/member/domain/MemberTest.java

- Member 테스트
- MemberFavorGenre 테스트
- lombok freefair 플러그인으로 변경 (8.11)
- 각 클래스에 생성자, 빌더 추가

test: Member 도메인 테스트

---

src/main/java/net/pointofviews/curation/domain/Curation.java
src/test/java/net/pointofviews/curation/domain/CurationTest.java

- Curation 빌더추가
- Curation Domain Test

feat: Curation 빌더 추가 및 도메인 테스트 작성

---

src/main/java/net/pointofviews/payment/domain/Payment.java
src/main/java/net/pointofviews/payment/domain/PaymentTransaction.java
src/test/java/net/pointofviews/payment/domain/PaymentTest.java
src/test/java/net/pointofviews/payment/domain/PaymentTransactionTest.java

- Payment, paymentTransaction 생성자, 빌더 추가
- Payment, paymentTransaction 테스트

test: Payment 도메인 테스트

---

src/main/java/net/pointofviews/club/domain/Club.java
src/main/java/net/pointofviews/club/domain/ClubFavorGenre.java
src/main/java/net/pointofviews/club/domain/ClubMovie.java
src/main/java/net/pointofviews/club/domain/MemberClub.java
src/test/java/net/pointofviews/club/domain/ClubFavorGenreTest.java
src/test/java/net/pointofviews/club/domain/ClubMovieTest.java
src/test/java/net/pointofviews/club/domain/ClubTest.java
src/test/java/net/pointofviews/club/domain/MemberClubTest.java

- club 관련 도메인 테스트 작성
- 생성자, 빌더 등 객체 생성에 필요한 메서드 작성
- Club의 maxParticipants 범위 제한 로직 작성

test: club 도메인 테스트 작성

---

src/main/java/net/pointofviews/premiere/domain/Entry.java
src/main/java/net/pointofviews/premiere/domain/Premiere.java
src/test/java/net/pointofviews/premiere/domain/EntryTest.java
src/test/java/net/pointofviews/premiere/domain/PremiereTest.java

- Entry,Premiere 엔티티에 생성자, 빌더 추가
- Payment, paymentTransaction 테스트코드 추가

test: premiere 도메인 테스트

---

src/main/java/net/pointofviews/common/config/JpaAuditingConfig.java
src/main/java/net/pointofviews/common/domain/CommonCode.java
src/main/java/net/pointofviews/common/domain/CommonCodeGroup.java
src/test/java/net/pointofviews/common/domain/CommonCodeGroupTest.java
src/test/java/net/pointofviews/common/domain/CommonCodeTest.java
src/test/java/net/pointofviews/curation/domain/CurationTest.java

- CommonCode Domain Test
- CommonCodeGroup Domain Test
- EnableJpaAuditing Config 분리

feat: Common 도메인 테스트 작성

---

build.gradle
src/main/java/net/pointofviews/common/config/SwaggerConfig.java
src/main/resources/application.yml

feat: Swagger 적용

---

src/main/java/net/pointofviews/notice/domain/Notice.java
src/main/java/net/pointofviews/notice/domain/NoticeReceive.java
src/main/java/net/pointofviews/notice/domain/NoticeSend.java
src/main/resources/db/migration/V1__init.sql
src/test/java/net/pointofviews/notice/domain/NoticeReceiveTest.java
src/test/java/net/pointofviews/notice/domain/NoticeSendTest.java
src/test/java/net/pointofviews/notice/domain/NoticeTest.java

- Notice 관련 도메인 테스트 및 객체 생성 메서드 작성
- Flyway 버전 동기화

test: notice 도메인 테스트

---

src/main/java/net/pointofviews/club/domain/Club.java
src/main/java/net/pointofviews/member/domain/Member.java
src/main/java/net/pointofviews/notice/domain/Notice.java
src/main/resources/db/migration/V1__init.sql
src/test/resources/application.yml

chore: flyway 수정

---

src/main/java/net/pointofviews/member/domain/Member.java
src/main/java/net/pointofviews/movie/domain/Actor.java
src/main/java/net/pointofviews/movie/domain/Award.java
src/main/java/net/pointofviews/movie/domain/Movie.java
src/main/java/net/pointofviews/movie/domain/MovieContent.java
src/main/java/net/pointofviews/movie/domain/MovieGenre.java
src/main/java/net/pointofviews/movie/domain/MovieLike.java
src/main/java/net/pointofviews/movie/domain/MovieLikeCount.java
src/main/java/net/pointofviews/movie/domain/RecommendedMovie.java
src/test/java/net/pointofviews/movie/domain/ActorTest.java
src/test/java/net/pointofviews/movie/domain/AwardTest.java
src/test/java/net/pointofviews/movie/domain/MovieContentTest.java
src/test/java/net/pointofviews/movie/domain/MovieGenreTest.java
src/test/java/net/pointofviews/movie/domain/MovieLikeCountTest.java
src/test/java/net/pointofviews/movie/domain/MovieLikeTest.java
src/test/java/net/pointofviews/movie/domain/MovieTest.java
src/test/java/net/pointofviews/movie/domain/RecommendedMovieTest.java

- movie 도메인 테스트 작성
- movie 도메인 entity 빌더 생성

feat: Movie domain 빌더 생성 및 테스트 작성

---

src/main/java/net/pointofviews/review/domain/Review.java
src/main/java/net/pointofviews/review/domain/ReviewKeywordLink.java
src/main/java/net/pointofviews/review/domain/ReviewLike.java
src/main/java/net/pointofviews/review/domain/ReviewLikeCount.java
src/test/java/net/pointofviews/review/domain/ReviewKeywordLinkTest.java
src/test/java/net/pointofviews/review/domain/ReviewLikeCountTest.java
src/test/java/net/pointofviews/review/domain/ReviewLikeTest.java
src/test/java/net/pointofviews/review/domain/ReviewTest.java

- 해당 엔티티 빌더 및 테스트 코드 추가(Review, ReviewKeywordLink, ReviewLike, ReviewLikeCount)

feat: review 도메인 테스트 작성

---

src/main/java/net/pointofviews/common/dto/ApiResponse.java
src/main/java/net/pointofviews/common/exception/BusinessException.java
src/main/java/net/pointofviews/common/exception/GlobalExceptionHandler.java

- GlobalException 및 ApiResponse 작성

feat: GlobalException 및 ApiResponse 작성

---

build.gradle
src/main/java/net/pointofviews/member/controller/AuthController.java
src/main/java/net/pointofviews/member/controller/AuthSpecification.java
src/main/java/net/pointofviews/member/controller/MemberController.java
src/main/java/net/pointofviews/member/controller/MemberSpecification.java
src/main/java/net/pointofviews/member/dto/request/CreateMemberRequest.java
src/main/java/net/pointofviews/member/dto/request/LoginMemberRequest.java
src/main/java/net/pointofviews/member/dto/request/PutMemberGenreListRequest.java
src/main/java/net/pointofviews/member/dto/request/PutMemberImageRequest.java
src/main/java/net/pointofviews/member/dto/request/PutMemberNicknameRequest.java
src/main/java/net/pointofviews/member/dto/request/PutMemberNoticeRequest.java
src/main/java/net/pointofviews/member/dto/response/CreateMemberResponse.java
src/main/java/net/pointofviews/member/dto/response/LoginMemberResponse.java
src/main/java/net/pointofviews/member/dto/response/PutMemberGenreListResponse.java
src/main/java/net/pointofviews/member/dto/response/PutMemberImageResponse.java
src/main/java/net/pointofviews/member/dto/response/PutMemberNicknameResponse.java
src/main/java/net/pointofviews/member/dto/response/PutMemberNoticeResponse.java
src/main/java/net/pointofviews/member/service/MemberService.java
src/main/java/net/pointofviews/member/service/impl/MemberServiceImpl.java
src/main/java/net/pointofviews/payment/domain/Payment.java

- member 관련 swagger 설정
- 기본 member service 파일 추가
- @Validated 의존성 추가
- auth 분리 (확인 필요)

feat: member 관련 swagger 설정

---

src/main/java/net/pointofviews/premiere/controller/PremiereController.java
src/main/java/net/pointofviews/premiere/controller/PremiereSpecification.java
src/main/java/net/pointofviews/premiere/dto/request/CreatePremiereRequest.java
src/main/java/net/pointofviews/premiere/dto/response/ReadDetailPremiereResponse.java
src/main/java/net/pointofviews/premiere/dto/response/ReadPremiereListResponse.java
src/main/java/net/pointofviews/premiere/dto/response/ReadPremiereResponse.java

feat: premiere 관련 메서드 Swagger 작성

---

src/main/java/net/pointofviews/review/controller/ReviewController.java
src/main/java/net/pointofviews/review/controller/ReviewSpecification.java
src/main/java/net/pointofviews/review/domain/Review.java
src/main/java/net/pointofviews/review/dto/request/CreateReviewRequest.java
src/main/java/net/pointofviews/review/dto/request/ProofreadReviewRequest.java
src/main/java/net/pointofviews/review/dto/request/PutReviewRequest.java
src/main/java/net/pointofviews/review/dto/response/ProofreadReviewResponse.java
src/main/java/net/pointofviews/review/dto/response/ReadReviewListResponse.java
src/main/java/net/pointofviews/review/dto/response/ReadReviewResponse.java
src/main/java/net/pointofviews/review/service/ReviewService.java
src/main/java/net/pointofviews/review/service/impl/ReviewServiceImpl.java
src/main/resources/db/migration/V1__init.sql
src/test/java/net/pointofviews/review/domain/ReviewTest.java

- Review Swagger 작성
- Review Entity 와 Flyway Review 에 preference 추가

feat: Review 관련 Swagger 명세서 작성

---

src/main/java/net/pointofviews/movie/domain/Movie.java
src/main/java/net/pointofviews/movie/domain/MovieLike.java
src/main/java/net/pointofviews/movie/domain/MovieLikeCount.java
src/main/java/net/pointofviews/movie/exception/MovieNotFoundException.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/review/controller/ReviewController.java
src/main/java/net/pointofviews/review/controller/ReviewSpecification.java
src/main/java/net/pointofviews/review/domain/Review.java
src/main/java/net/pointofviews/review/domain/ReviewLike.java
src/main/java/net/pointofviews/review/dto/response/ReadReviewListResponse.java
src/main/java/net/pointofviews/review/repository/ReviewLikeCountRepository.java
src/main/java/net/pointofviews/review/repository/ReviewLikeRepository.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/java/net/pointofviews/review/service/ReviewService.java
src/main/java/net/pointofviews/review/service/impl/ReviewServiceImpl.java
src/main/resources/db/migration/V1__init.sql
src/test/java/net/pointofviews/movie/domain/MovieLikeCountTest.java

- ReviewLike, MovieLike 에 isLiked 추가
- Review, Movie 연관관계 매핑 & 무한방지 메소드 추가
- Flyway 수정
- Review 테이블: thumbnail, movie_id 추가
- ReviewLiked, MovieLiked 테이블: isLiked 추가

feat: 영화별 리뷰 조회 구현

---

build.gradle
src/main/java/net/pointofviews/auth/config/CorsConfig.java
src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java
src/main/java/net/pointofviews/auth/controller/AuthController.java
src/main/java/net/pointofviews/auth/controller/AuthSpecification.java
src/main/java/net/pointofviews/auth/dto/request/CreateMemberRequest.java
src/main/java/net/pointofviews/auth/dto/request/LoginMemberRequest.java
src/main/java/net/pointofviews/auth/dto/response/CreateMemberResponse.java
src/main/java/net/pointofviews/auth/dto/response/LoginMemberResponse.java
src/main/java/net/pointofviews/auth/utils/JwtProvider.java
src/main/java/net/pointofviews/common/exception/BadRequestException.java
src/main/java/net/pointofviews/member/service/MemberService.java
src/main/java/net/pointofviews/member/service/impl/MemberServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/test/resources/application.yml

- security, oauth2, jjwt 의존성 주입
- cors 설정
- JwtProvider 샘플 작성

feat: security 기초 작업

---

src/main/resources/application-dev.yml

feat: dev-yml s3 key 환경변수 설정

---

src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java
src/main/resources/application.yml

feat: actuator 경로 api/actuator로 변경

---

src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java
src/main/java/net/pointofviews/auth/utils/JwtProvider.java
src/main/java/net/pointofviews/common/exception/BadRequestException.java
src/main/java/net/pointofviews/movie/controller/MovieSpecification.java
src/main/java/net/pointofviews/movie/exception/MovieException.java
src/main/java/net/pointofviews/review/controller/ReviewController.java
src/main/java/net/pointofviews/review/controller/ReviewSpecification.java
src/main/java/net/pointofviews/review/exception/ReviewException.java
src/main/java/net/pointofviews/review/exception/ReviewNotFoundException.java
src/main/java/net/pointofviews/review/repository/ReviewLikeCountRepository.java
src/main/java/net/pointofviews/review/service/impl/ReviewServiceImpl.java
src/test/java/net/pointofviews/review/service/ReviewServiceTest.java

- 리뷰 상세 조회 구현
- Swagger 관련 경로 permitAll 로 설정
- ReviewSpecification 의 `readReviewDetail()` 에 swagger Parameter 추가
- ReviewSpecification 에서 존재하지 않는 상태 코드 400 → 404 로 변경
- ReviewController 에 `/api` prefix 추가
> 비즈니스 로직 테스트
> 정상 응답
> 존재하지 않는 리뷰일 경우 예외 발생

feat: 리뷰 상세 조회 구현

---

src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java
src/main/resources/application.yml

refactor: swagger 경로 변경 및 security 제한 해제

---

src/main/java/net/pointofviews/review/controller/ReviewController.java
src/main/java/net/pointofviews/review/controller/ReviewSpecification.java
src/main/java/net/pointofviews/review/domain/Review.java
src/main/java/net/pointofviews/review/service/impl/ReviewServiceImpl.java

feat: 리뷰 숨김 구현

---

src/main/resources/db/migration/V1__init.sql
src/test/java/net/pointofviews/member/domain/MemberTest.java

refactor: member 수정 관련 테스트코드 및 flyway 반영

---

.github/workflows/cicd.yml

feat: tmdb access token setting

---

src/main/resources/application.yml

feat: swagger path 변경

---

src/main/java/net/pointofviews/review/dto/response/ReadReviewResponse.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/test/java/net/pointofviews/review/service/ReviewMemberServiceTest.java

refactor: 리뷰 DTO 에 reviewId 추가

---

src/test/java/net/pointofviews/member/service/MemberServiceTest.java

refactor: USER 수정

---

src/test/java/net/pointofviews/member/service/MemberServiceTest.java

- 회원 선호 장르 변경 비즈니스 로직 단위 테스트 작성

feat: 회원 선호 장르 변경 비즈니스 로직 단위 테스트 작성

---

src/main/java/net/pointofviews/movie/controller/MovieAdminController.java
src/main/java/net/pointofviews/movie/controller/MovieAdminSpecification.java
src/main/java/net/pointofviews/movie/dto/response/SearchMovieApiResponse.java
src/main/java/net/pointofviews/movie/dto/response/SearchMovieDetailApiResponse.java
src/main/java/net/pointofviews/movie/service/MovieApiSearchService.java
src/main/java/net/pointofviews/movie/service/MovieTMDbSearchService.java
src/test/java/net/pointofviews/movie/service/MovieTMDbSearchServiceTest.java

- 영화 조회 시 장르 Id 조회에서 장르 이름 조회로 변경
- TMDb의 영화 id를 이용한 영화 상세 조회 기능 작성

feat: TMDb 영화 상세 조회 기능 작성

---

src/test/java/net/pointofviews/review/service/ReviewClubServiceTest.java

- 클럽별 리뷰 전체 조회 비즈니스 로직 단위 테스트 작성

feat: 클럽별 리뷰 전체 조회 비즈니스 로직 단위 테스트 작성

---

src/main/java/net/pointofviews/review/controller/ReviewMemberController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewMemberSpecification.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/java/net/pointofviews/review/service/ReviewMemberService.java
src/main/java/net/pointofviews/review/service/impl/ReviewMemberServiceImpl.java

feat: 내 리뷰 전체 조회 구현

---

.github/workflows/cicd.yml
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/resources/application.yml

- application.yml 수정
-  cicd.yml 수정

feat: application 수정

---

src/test/java/net/pointofviews/review/service/ReviewClubServiceTest.java
src/test/java/net/pointofviews/review/service/ReviewMemberServiceTest.java

- ReviewClubService, ReviewMemberService 수정

refactor: ReviewClubService, ReviewMemberService 수정

---

src/main/java/net/pointofviews/movie/domain/MovieCast.java
src/main/java/net/pointofviews/movie/domain/MovieCrew.java
src/main/java/net/pointofviews/movie/domain/People.java
src/main/resources/db/migration/V1__init.sql

refactor: MoviePeople 테이블을 MovieCast, MovieCrew 테이블로 분리, people 테이블 컬럼 추가

---

src/main/java/net/pointofviews/common/exception/CommonCodeException.java
src/main/java/net/pointofviews/common/service/CommonCodeService.java
src/main/java/net/pointofviews/common/service/S3Service.java
src/main/java/net/pointofviews/common/service/impl/CommonCodeServiceImpl.java
src/main/java/net/pointofviews/common/service/impl/S3ServiceImpl.java
src/main/java/net/pointofviews/review/controller/ReviewMemberController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewMemberSpecification.java
src/main/java/net/pointofviews/review/domain/Review.java
src/main/java/net/pointofviews/review/dto/request/CreateReviewRequest.java
src/main/java/net/pointofviews/review/dto/request/PutReviewRequest.java
src/main/java/net/pointofviews/review/exception/ReviewException.java
src/main/java/net/pointofviews/review/repository/ReviewKeywordLinkRepository.java
src/main/java/net/pointofviews/review/service/ReviewMemberService.java
src/main/java/net/pointofviews/review/service/impl/ReviewMemberServiceImpl.java
src/test/java/net/pointofviews/common/service/CommonCodeServiceImplTest.java
src/test/java/net/pointofviews/member/service/MemberServiceTest.java
src/test/java/net/pointofviews/review/service/ReviewMemberServiceTest.java

- 리뷰 등록, 수정, 삭제 인증 추가
- 리뷰내 이미지 관련 로직 수정 (이미지 등록 경로, 삭제 로직)
- 키워드 변환 로직 수정
- 관련 테스트 수정
- 사용하지 않는 메소드 삭제 및 범용적인 명칭으로 메소드명 수정
- 리뷰 수정가능 데이터 추가
-------------------------

refactor: 리뷰 등록, 수정, 삭제 관련 수정

---

src/main/java/net/pointofviews/common/exception/CommonCodeException.java
src/main/java/net/pointofviews/common/exception/GlobalExceptionHandler.java
src/main/java/net/pointofviews/common/service/CommonCodeService.java
src/main/java/net/pointofviews/common/service/impl/CommonCodeServiceImpl.java
src/main/java/net/pointofviews/movie/domain/Country.java
src/main/java/net/pointofviews/movie/domain/FilmRatingConverter.java
src/main/java/net/pointofviews/movie/domain/KoreanFilmRating.java
src/main/java/net/pointofviews/movie/domain/Movie.java
src/main/java/net/pointofviews/movie/domain/MovieCast.java
src/main/java/net/pointofviews/movie/domain/MovieCountry.java
src/main/java/net/pointofviews/movie/domain/MovieGenre.java
src/main/java/net/pointofviews/movie/domain/People.java
src/main/resources/db/migration/V1__init.sql
src/test/java/net/pointofviews/movie/domain/MovieTest.java
src/test/java/net/pointofviews/movie/domain/PeopleTest.java

- Country 추가
- MovieCountry 추가
- schema 변경

feat: Country, MovieCountry 추가 및 스키마 변경

---

src/main/java/net/pointofviews/auth/controller/AuthController.java
src/main/java/net/pointofviews/auth/security/JwtAuthenticationFilter.java
src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/ClubSpecification.java
src/main/java/net/pointofviews/club/dto/request/CreateClubRequest.java
src/main/java/net/pointofviews/club/dto/request/PutClubLeaderRequest.java
src/main/java/net/pointofviews/club/dto/request/PutClubRequest.java
src/main/java/net/pointofviews/club/dto/response/CreateClubImageListResponse.java
src/main/java/net/pointofviews/club/dto/response/CreateClubResponse.java
src/main/java/net/pointofviews/club/dto/response/PutClubLeaderResponse.java
src/main/java/net/pointofviews/club/dto/response/PutClubResponse.java
src/main/java/net/pointofviews/club/service/ClubService.java
src/main/java/net/pointofviews/club/service/ClubServiceImpl.java
src/main/java/net/pointofviews/movie/domain/Country.java
src/main/java/net/pointofviews/movie/domain/MovieCountry.java
src/main/resources/db/migration/V1__init.sql

- flyway 전체적인 수정내용 반영
- 클럽 등록 관련 초기 설정
- refreshToken 관련 수정 (sameSite 설정 추가)

refactor: flyway 수정

---

src/main/java/net/pointofviews/movie/controller/MovieAdminSpecification.java
src/main/java/net/pointofviews/movie/controller/MovieController.java
src/main/java/net/pointofviews/movie/controller/MovieMemberController.java
src/main/java/net/pointofviews/movie/controller/MovieSpecification.java
src/main/java/net/pointofviews/movie/dto/response/SearchMovieResponse.java
src/main/java/net/pointofviews/movie/exception/PeopleException.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/movie/service/MovieSearchService.java
src/main/java/net/pointofviews/movie/service/impl/MovieSearchServiceImpl.java
src/main/resources/db/migration/V3__add_fulltext_ngram_index.sql

- flyway V3 추가 (full text seach-ngram 인덱스 생성)
- 영화 검색 기능
- 테스트는 클럽 검색 구현 후에 함께 추가 예정

feat: full text search를 이용한 영화 검색 기능 구현

---

src/test/java/net/pointofviews/PovApplicationTests.java

feat: 테스트 임시 제거

---

src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/ClubSpecification.java
src/main/java/net/pointofviews/club/domain/Club.java
src/main/java/net/pointofviews/club/domain/MemberClub.java
src/main/java/net/pointofviews/club/dto/request/CreateClubRequest.java
src/main/java/net/pointofviews/club/dto/request/PutClubRequest.java
src/main/java/net/pointofviews/club/dto/response/CreateClubResponse.java
src/main/java/net/pointofviews/club/exception/ClubException.java
src/main/java/net/pointofviews/club/repository/ClubFavorGenreRepository.java
src/main/java/net/pointofviews/club/repository/ClubRepository.java
src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/club/service/ClubService.java
src/main/java/net/pointofviews/club/service/ClubServiceImpl.java
src/main/java/net/pointofviews/common/exception/S3Exception.java
src/main/java/net/pointofviews/common/service/S3Service.java
src/main/java/net/pointofviews/common/service/impl/S3ServiceImpl.java
src/test/java/net/pointofviews/club/service/ClubServiceImplTest.java

- 클럽 생성, 수정, 삭제 / 클럽 탈퇴, 클럽장 변경 / 클럽 이미지 등록, 수정 기능 추가
- 현재 flyway관련 테스트오류 확인, 수정코드 pull받은 후 현 pr merge 예정

feat: 클럽 관련 기능 및 테스트 추가

---

src/main/java/net/pointofviews/country/domain/Country.java
src/main/java/net/pointofviews/country/repository/CountryRepository.java
src/main/java/net/pointofviews/movie/controller/MovieAdminController.java
src/main/java/net/pointofviews/movie/domain/MovieCast.java
src/main/java/net/pointofviews/movie/domain/MovieCountry.java
src/main/java/net/pointofviews/movie/domain/MovieCrew.java
src/main/java/net/pointofviews/movie/domain/MovieGenre.java
src/main/java/net/pointofviews/movie/dto/request/CreateMovieRequest.java
src/main/java/net/pointofviews/movie/exception/MovieException.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/movie/service/MovieCountryService.java
src/main/java/net/pointofviews/movie/service/MoviePeopleService.java
src/main/java/net/pointofviews/movie/service/MovieService.java
src/main/java/net/pointofviews/movie/service/impl/MovieCountryServiceImpl.java
src/main/java/net/pointofviews/movie/service/impl/MoviePeopleServiceImpl.java
src/main/java/net/pointofviews/movie/service/impl/MovieServiceImpl.java
src/main/java/net/pointofviews/people/domain/People.java
src/main/java/net/pointofviews/people/repository/PeopleRepository.java
src/test/java/net/pointofviews/movie/domain/PeopleTest.java
src/test/java/net/pointofviews/movie/service/MovieCountryServiceImplTest.java
src/test/java/net/pointofviews/movie/service/MoviePeopleServiceImplTest.java

- 영화 저장 기능 작성
- 영화 인물 저장 기능 작성
- 영화 국가 저장 기능 작성
- 영화 관련 장르 저장 기능 작성
- 테스트
- 각 영화를 저장할 때 인물들을 함께 저장해야 했는데 트랜잭션을 관리하는 과정에서 성능 이슈가 발생.
- 추후 WebFlux와 같은 비동기 기능을 사용해 볼 여지가 있을 것 같습니다.

feat: 영화 저장 기능 작성

---

src/main/java/net/pointofviews/premiere/controller/PremiereAdminController.java
src/main/java/net/pointofviews/premiere/controller/specification/PremiereAdminSpecification.java
src/main/java/net/pointofviews/premiere/dto/request/PremiereRequest.java
src/main/java/net/pointofviews/premiere/dto/response/ReadDetailPremiereResponse.java
src/main/java/net/pointofviews/premiere/service/PremiereAdminService.java
src/main/java/net/pointofviews/premiere/service/imple/PremiereAdminServiceImpl.java
src/test/java/net/pointofviews/premiere/service/PremiereAdminServiceTest.java

- 관리자 시사회 상세 조회 구현
- 관리자 시사회 상세 조회 테스트 작성
> 관리자 시사회 상세 조회
> 관리자 시사회 상세 조회 테스트

feat: 관리자 시사회 상세 조회 구현 및 단위 테스트 작성

---

src/main/java/net/pointofviews/auth/controller/AuthController.java
src/main/java/net/pointofviews/auth/security/JwtAuthenticationFilter.java

- accessToken, refreshToken 유효시간 롤백(각 1시간, 2주)
- 새로운 at를 처리하는 과정에서 같은 코드가 반복되는 부분 리팩토링

refactor: at, rt 유효시간 변경 및 중복코드 리팩토링

---

src/main/java/net/pointofviews/premiere/controller/PremiereMemberController.java
src/main/java/net/pointofviews/premiere/controller/specification/PremiereMemberSpecification.java
src/main/java/net/pointofviews/premiere/service/PremiereMemberService.java
src/main/java/net/pointofviews/premiere/service/impl/PremiereMemberServiceImpl.java
src/test/java/net/pointofviews/premiere/service/PremiereMemberServiceTest.java

- 회원 시사회 상세 조회 구현 
- 회원 시사회 상세 조회 테스트 작성
> 회원 시사회 상세 조회
> 회원 시사회 상세 조회 테스트

feat: 회원 시사회 상세 조회 구현 및 단위 테스트 작성

---

src/main/java/net/pointofviews/club/dto/response/FindBasicClubInfo.java
src/main/java/net/pointofviews/club/dto/response/ReadClubDetailsResponse.java
src/main/java/net/pointofviews/club/repository/ClubRepository.java
src/main/java/net/pointofviews/club/service/impl/ClubServiceImpl.java
src/test/java/net/pointofviews/club/service/ClubServiceImplTest.java

- 클럽 상세 조회 response (maxParticipants) 추가
- 클럽 상세 조회 테스트 코드 수정

feat: 클럽 상세 조회 응답 추가 (최대 인원 수) 및 테스트 수정

---

src/main/java/net/pointofviews/premiere/controller/PremiereAdminController.java
src/main/java/net/pointofviews/premiere/controller/PremiereMemberController.java
src/main/java/net/pointofviews/premiere/controller/specification/PremiereAdminSpecification.java
src/main/java/net/pointofviews/premiere/controller/specification/PremiereMemberSpecification.java
src/main/java/net/pointofviews/premiere/dto/response/ReadPremiereListResponse.java
src/main/java/net/pointofviews/premiere/dto/response/ReadPremierePageResponse.java
src/main/java/net/pointofviews/premiere/service/PremiereAdminService.java
src/main/java/net/pointofviews/premiere/service/PremiereMemberService.java
src/main/java/net/pointofviews/premiere/service/impl/PremiereAdminServiceImpl.java
src/main/java/net/pointofviews/premiere/service/impl/PremiereMemberServiceImpl.java
src/test/java/net/pointofviews/premiere/service/PremiereAdminServiceTest.java
src/test/java/net/pointofviews/premiere/service/PremiereMemberServiceTest.java

- 회원 시사회 전체 조회 구현
- 회원 시사회 전체 조회 테스트 작성
> 회원 시사회 전체 조회
> 회원 시사회 전체 조회 테스트

feat: 회원 시사회 전체 조회 구현 및 단위 테스트 작성

---

src/main/java/net/pointofviews/movie/batch/config/JobLauncherRunner.java
src/main/java/net/pointofviews/movie/batch/config/MovieBatchConfig.java
src/main/java/net/pointofviews/movie/batch/config/MovieChunkListener.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryProcessor.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryReader.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryStep.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryWriter.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditProcessor.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditReader.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditStep.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditWriter.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverProcessor.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverStep.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseProcessor.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseReader.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseStep.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseWriter.java
src/main/java/net/pointofviews/movie/controller/MovieAdminController.java
src/main/java/net/pointofviews/movie/domain/KoreanFilmRating.java
src/main/java/net/pointofviews/movie/domain/Movie.java
src/main/java/net/pointofviews/movie/domain/MovieCountry.java
src/main/java/net/pointofviews/movie/dto/response/CreditProcessorResponse.java
src/main/java/net/pointofviews/movie/service/MovieApiSearchService.java
src/main/java/net/pointofviews/movie/service/impl/MovieTMDbSearchService.java
src/test/java/net/pointofviews/movie/service/MovieTMDbSearchServiceTest.java

- 영화 심의등급, 상영일자 추가 ( release date api)
- 영화 제작 국가 추가 ( deatils api )
- cascade를 이용하여 다소 비효율적인 쿼리가 나가더라도 일단 올려두겠습니다.

feat: 영화 정보 배치 삽입 기능 작성

---

src/test/java/net/pointofviews/movie/service/MovieTMDbSearchServiceTest.java

test: 영화 배우 10명에서 5명으로 변경

---

src/main/java/net/pointofviews/auth/config/CorsConfig.java

feat: cors localhost 해제

---

src/main/java/net/pointofviews/curation/service/impl/CurationMovieRedisServiceImpl.java

refactor: CurationMovieRedisServiceImpl test 오류 수정

---

src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java

- softDelete된 리뷰를 제외한 리뷰만 조회도록 수정

refactor: softDelete된 리뷰를 제외한 리뷰만 조회도록 수정

---

src/main/java/net/pointofviews/review/repository/ReviewRepository.java

refactor: 리뷰 조회 응답값 수정

---

src/main/java/net/pointofviews/club/dto/response/ReadClubDetailsResponse.java
src/main/java/net/pointofviews/club/service/impl/ClubServiceImpl.java
src/test/java/net/pointofviews/club/service/ClubServiceImplTest.java

- 클럽 상세 조회 응답 수정
- 클럽 상세 조회 테스트 수정

refactor: 클럽 상세 조회 수정

---

src/main/java/net/pointofviews/movie/repository/MovieContentRepository.java

refactor: 빌드 오류 수정

---

src/main/java/net/pointofviews/notice/controller/NoticeController.java
src/main/java/net/pointofviews/notice/domain/NoticeReceive.java
src/main/java/net/pointofviews/notice/dto/response/ReadNoticeResponse.java
src/main/java/net/pointofviews/notice/service/NoticeServiceImpl.java
src/main/resources/db/migration/V6__add_review_id_to_notice_receive.sql

- 알림 수신시 notice_receive에 저장되도록 수정
- 알림을 읽으면(알림 조회에서 알림을 클릭해 해당 리뷰로 이동하면) 알림 내용삭제
- 알림 조회시 response로 reviewId 추가

refactor: 알림 조회 및 읽음처리 수정

---

src/main/java/net/pointofviews/notice/dto/response/ReadNoticeResponse.java
src/main/java/net/pointofviews/notice/repository/NoticeReceiveRepository.java
src/main/java/net/pointofviews/notice/service/NoticeServiceImpl.java
src/main/java/net/pointofviews/notice/utils/FcmUtil.java

- 알림 조회시 movieId값 추가
- 본인 리뷰에 대한 알림은 제외
- fcm 알림시 500개 토큰을 한번에 전송하도록 수정

refactor: 알림 관련 수정

---

src/main/java/net/pointofviews/member/service/MemberRedisService.java
src/main/java/net/pointofviews/member/service/impl/MemberRedisServiceImpl.java
src/main/java/net/pointofviews/notice/utils/FcmUtil.java
src/main/java/net/pointofviews/review/service/ReviewNotificationService.java
src/main/java/net/pointofviews/review/service/impl/ReviewNotificationServiceImpl.java
src/test/java/net/pointofviews/member/service/MemberServiceTest.java

- 프론트와 테스트시 알림 전송단계에서 firebase 문제 발생 -> 배치작업으로 한번에 토큰전달하는 부분 수정
- 인터페이스와 구현체 분리 안된 부분(ReviewNotificationService, MemberRedisService) 수정
에러 내용 : Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found POST https://fcm.googleapis.com/batch

refactor: firebase 404에러 수정

---

src/main/java/net/pointofviews/notice/utils/FcmUtil.java

- https://fcm.googleapis.com/batch api 자체가 서비스 종료됨에 따라 일괄 알림 발송 로직 롤백

refactor: 일괄 알림 발송 롤백

---

src/main/java/net/pointofviews/payment/service/impl/TempPaymentServiceImpl.java
src/main/java/net/pointofviews/premiere/controller/EntryController.java
src/main/java/net/pointofviews/premiere/controller/specification/EntrySpecification.java
src/main/java/net/pointofviews/premiere/dto/response/ReadEntryResponse.java
src/main/java/net/pointofviews/premiere/dto/response/ReadMyEntryListResponse.java
src/main/java/net/pointofviews/premiere/repository/EntryRepository.java
src/main/java/net/pointofviews/premiere/service/EntryService.java
src/main/java/net/pointofviews/premiere/service/impl/EntryServiceImpl.java
src/main/java/net/pointofviews/review/controller/ReviewClubController.java

- 내 시사회 티켓팅 내역 조회 구현
- 가입한 클럽 목록 조회 API 수정

feat: 내 시사회 티켓팅 내역 조회 구현

---

src/main/java/net/pointofviews/common/toss/TossProperty.java

- secretKey에 콜론 추가하여 Base64 인코딩

fix: secretKey에 콜론 추가하여 Base64 인코딩

---

src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/specification/ClubSpecification.java
src/main/java/net/pointofviews/club/dto/response/ReadAllClubMembersResponse.java
src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/club/service/MemberClubService.java
src/main/java/net/pointofviews/club/service/impl/MemberClubServiceImpl.java
src/test/java/net/pointofviews/club/service/MemberClubServiceImplTest.java

- 클럽 멤버 전체 조회 기능 작성
- 테스트 작성
- swagger 수정

feat: 클럽 멤버 전체 조회 기능 작성

---

src/main/java/net/pointofviews/club/dto/response/ClubMemberResponse.java
src/main/java/net/pointofviews/club/dto/response/ReadAllClubMembersResponse.java
src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/club/service/impl/MemberClubServiceImpl.java
src/test/java/net/pointofviews/club/service/MemberClubServiceImplTest.java

refactor: ClubMemberResponse 분리

---

src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/specification/ClubSpecification.java
src/main/java/net/pointofviews/club/exception/ClubException.java
src/main/java/net/pointofviews/club/exception/InviteCodeException.java
src/main/java/net/pointofviews/club/repository/ClubRepository.java
src/main/java/net/pointofviews/club/service/MemberClubService.java
src/main/java/net/pointofviews/club/service/impl/MemberClubServiceImpl.java
src/main/java/net/pointofviews/club/utils/InviteCodeGenerator.java
src/main/java/net/pointofviews/common/config/SwaggerConfig.java
src/main/java/net/pointofviews/common/exception/RedisException.java
src/main/java/net/pointofviews/common/repository/RedisRepository.java
src/main/java/net/pointofviews/common/repository/impl/StringRedisRepositoryImpl.java
src/main/java/net/pointofviews/common/service/RedisService.java
src/main/java/net/pointofviews/common/service/impl/StringRedisServiceImpl.java
src/test/java/net/pointofviews/club/service/MemberClubServiceImplTest.java
src/test/java/net/pointofviews/club/utils/InviteCodeGeneratorTest.java
src/test/java/net/pointofviews/common/service/RedisServiceTest.java

- 클럽 초대 코드 생성 기능 작성
- redis 기능 분리
- 테스트 작성
- 스웨거 인증 기능 작성

feat: 클럽 초대 코드 생성 기능 작성

---

src/main/java/net/pointofviews/member/controller/MemberController.java
src/main/java/net/pointofviews/member/controller/MemberSpecification.java
src/main/java/net/pointofviews/member/service/MemberService.java
src/main/java/net/pointofviews/member/service/impl/MemberServiceImpl.java

- 로그아웃시 cookie 내 refreshToken 제거
- logout 구현부에 fcm 토큰 비활성화 여부 결정 필요

feat: logout api 추가

---

src/main/java/net/pointofviews/payment/domain/Payment.java
src/main/java/net/pointofviews/payment/dto/response/ConfirmPaymentResponse.java
src/main/java/net/pointofviews/payment/service/impl/PaymentServiceImpl.java
src/main/java/net/pointofviews/payment/service/impl/TempPaymentServiceImpl.java
src/main/java/net/pointofviews/premiere/controller/EntryController.java
src/main/java/net/pointofviews/premiere/controller/specification/EntrySpecification.java
src/main/java/net/pointofviews/premiere/dto/request/DeleteEntryRequest.java
src/main/java/net/pointofviews/premiere/exception/EntryException.java
src/main/java/net/pointofviews/premiere/repository/EntryRepository.java
src/main/java/net/pointofviews/premiere/service/EntryService.java
src/main/java/net/pointofviews/premiere/service/impl/EntryServiceImpl.java
src/main/resources/db/migration/V1.8__drop_payment_column.sql
src/test/java/net/pointofviews/payment/domain/PaymentTest.java

- 응모한 시사회 취소 구현
- 결제 관련 서비스단에서 예외가 발생하기 전 로그 기록하도록 추가
- Flyway V1.8 - 결제(Payment) 에서 불필요한 Member 필드 및 컬럼 제거

feat: 응모한 시사회 취소 구현

---

src/main/java/net/pointofviews/movie/domain/MovieLikeCount.java

- movieLikeCountTest 에러 부분 해결: LikeCount 초기값 설정

refactor: movieLikeCount의 기본값 0으로 초기화

---

src/main/java/net/pointofviews/review/controller/ReviewAdminController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewAdminSpecification.java
src/main/java/net/pointofviews/review/dto/response/SearchReviewListResponse.java
src/main/java/net/pointofviews/review/dto/response/SearchReviewResponse.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/java/net/pointofviews/review/service/ReviewAdminService.java
src/main/java/net/pointofviews/review/service/impl/ReviewAdminServiceImpl.java
src/main/resources/db/migration/V1.9__update_temp_payment_schema.sql

- 관리자 영화명 검색을 통한 리뷰 전체 조회 시 최신 순으로 조회
- Flyway V1.9 TempPayment - Member UK 설정 제거

feat: 관리자 영화명 검색을 통한 리뷰 전체 조회 구현

---

.github/workflows/cicd.yml
src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java
src/main/java/net/pointofviews/auth/dto/MemberDetailsDto.java
src/main/java/net/pointofviews/auth/dto/NaverUserDetails.java
src/main/java/net/pointofviews/auth/dto/OAuth2UserInfo.java
src/main/java/net/pointofviews/auth/exception/SecurityException.java
src/main/java/net/pointofviews/auth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/net/pointofviews/auth/service/CustomOauth2UserService.java
src/main/resources/application-dev.yml

feat: Naver OAuth2 로그인 기능 작성 및 api/auth/login 리디렉션

---

src/main/java/net/pointofviews/review/service/impl/ReviewMemberServiceImpl.java

- thumbnail 값을 poster -> backdrop 으로 변경

refactor: thumbnail 값을 poster -> backdrop 으로 변경

---

src/main/java/net/pointofviews/auth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/net/pointofviews/common/config/TimeZoneConfig.java
src/main/java/net/pointofviews/movie/batch/config/JobLauncherRunner.java
src/main/java/net/pointofviews/movie/batch/config/TMDbMovieBatchScheduler.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryReader.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditReader.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverWriter.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseReader.java
src/main/java/net/pointofviews/movie/batch/repository/JobExecutionRepository.java
src/main/java/net/pointofviews/movie/controller/MovieAdminController.java
src/main/java/net/pointofviews/movie/controller/specification/MovieAdminSpecification.java
src/main/java/net/pointofviews/movie/dto/response/ReadDetailMovieResponse.java
src/main/java/net/pointofviews/movie/dto/response/SearchMovieImageApiResponse.java
src/main/java/net/pointofviews/movie/service/MovieApiSearchService.java
src/main/java/net/pointofviews/movie/service/impl/MovieSearchServiceImpl.java
src/main/java/net/pointofviews/movie/service/impl/MovieTMDbSearchService.java
src/main/resources/application-dev.yml

- 타임존 설정
- 영화 배치 매일 오전 3시 실행
- 영화 정보 매일 최신화
- 네이버 로그인 시 리디렉션 경로 변경

feat: TMDB 영화 배치 방법 변경

---

src/main/java/net/pointofviews/member/controller/MemberController.java
src/main/java/net/pointofviews/movie/controller/MovieController.java
src/main/java/net/pointofviews/review/dto/ReviewDetailsWithLikeCountDto.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/resources/application-dev.yml
src/test/java/net/pointofviews/movie/service/MovieSearchServiceImplTest.java

feat: 영화 상세조회 시 response 변경, 쿼리 변경

---

src/main/java/net/pointofviews/auth/handler/OAuth2AuthenticationSuccessHandler.java

feat: 네이버로그인 시 로그 작성

---

src/main/resources/application-dev.yml

feat: redirect url 변경

---

src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/club/service/impl/ClubServiceImpl.java
src/main/java/net/pointofviews/review/controller/ReviewClubController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewClubSpecification.java
src/main/java/net/pointofviews/review/service/ReviewClubService.java
src/main/java/net/pointofviews/review/service/impl/ReviewClubServiceImpl.java
src/main/resources/application-local.yml
src/test/java/net/pointofviews/club/service/ClubServiceImplTest.java
src/test/java/net/pointofviews/review/service/ReviewClubServiceTest.java

- 내 클럽에서 리뷰 조회시 로그인한 사용자 별 좋아요 표시 기능으로 나타나게 수정
- 관련 테스트 수정
- OAuth BaseUrl 추가

refactor: 로그인 사용자의 리뷰 좋아요 표시 기능 및 테스트 수정

---

src/main/resources/application-dev.yml

feat: 리다이렉트 url 로컬호스트로 변경

---

src/test/java/net/pointofviews/curation/service/CurationAdminServiceTest.java
src/test/java/net/pointofviews/curation/service/CurationMemberServiceImplTest.java
src/test/java/net/pointofviews/curation/service/CurationRedisServiceImplTest.java
src/test/java/net/pointofviews/curation/service/CurationSchedulerServiceImplTest.java

feat: 큐레이션 테스트 임시 주석 처리

---

src/main/java/net/pointofviews/member/repository/MemberFavorGenreRepository.java
src/main/java/net/pointofviews/movie/dto/response/ReadDetailMovieResponse.java

feat: islike boolean 타입 변경

---

src/main/java/net/pointofviews/movie/controller/specification/MovieSpecification.java

feat: 빌드 오류 수정

---

src/main/java/net/pointofviews/auth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/net/pointofviews/auth/service/CustomOauth2UserService.java

feat: naver OAuth2 시 프로필 정보만 반환

---

src/main/java/net/pointofviews/auth/config/GlobalSecurityConfig.java

feat: security 설정 변경

---

src/main/java/net/pointofviews/review/dto/ReviewDetailsWithLikeCountDto.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/resources/application-dev.yml
src/test/java/net/pointofviews/movie/service/MovieSearchServiceImplTest.java

feat: 리뷰 좋아요 여부 추가

---

src/main/java/net/pointofviews/review/controller/ReviewMemberController.java

refactor: 리뷰 좋아요 메서드 변경

---

src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/club/service/impl/ClubServiceImpl.java
src/main/java/net/pointofviews/review/controller/ReviewClubController.java
src/main/java/net/pointofviews/review/controller/ReviewMemberController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewClubSpecification.java
src/main/java/net/pointofviews/review/controller/specification/ReviewMemberSpecification.java
src/main/java/net/pointofviews/review/repository/ReviewLikeRepository.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/java/net/pointofviews/review/service/ReviewClubService.java
src/main/java/net/pointofviews/review/service/ReviewMemberService.java
src/main/java/net/pointofviews/review/service/impl/ReviewClubServiceImpl.java
src/main/java/net/pointofviews/review/service/impl/ReviewMemberServiceImpl.java
src/test/java/net/pointofviews/club/service/ClubServiceImplTest.java
src/test/java/net/pointofviews/review/service/ReviewClubServiceTest.java
src/test/java/net/pointofviews/review/service/ReviewMemberServiceTest.java

- 리뷰 조회 시 회원/비회원 구분한 isLiked 응답값 수정

refactor: 리뷰 조회 시 회원/비회원 구분한 isLiked 응답값 수정

---

src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/specification/ClubSpecification.java
src/main/java/net/pointofviews/movie/batch/config/MovieBatchConfig.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverWriter.java
src/main/java/net/pointofviews/movie/batch/dto/MovieContentsDto.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageProcessor.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageReader.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageStep.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageWriter.java
src/main/java/net/pointofviews/movie/batch/repository/JobExecutionRepository.java
src/main/java/net/pointofviews/movie/controller/MovieController.java
src/main/java/net/pointofviews/movie/service/MovieSearchService.java
src/main/java/net/pointofviews/movie/service/impl/MovieSearchServiceImpl.java
src/main/java/net/pointofviews/review/controller/ReviewMemberController.java
src/main/java/net/pointofviews/review/controller/specification/ReviewMemberSpecification.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/main/java/net/pointofviews/review/service/ReviewMemberService.java
src/main/java/net/pointofviews/review/service/impl/ReviewMemberServiceImpl.java
src/main/resources/application-dev.yml
src/test/java/net/pointofviews/movie/service/MovieSearchServiceImplTest.java
src/test/java/net/pointofviews/review/service/ReviewMemberServiceTest.java

- Tmdb image batch 기능 작성
- 배치 기준 시작일 2015. 01. 01 로 변경
- 비회원 이용가능 기능 리팩토링

feat: tmdb image batch 기능 작성

---

src/main/java/net/pointofviews/movie/batch/config/JobLauncherRunner.java
src/main/java/net/pointofviews/movie/batch/config/MovieBatchConfig.java
src/main/java/net/pointofviews/movie/batch/config/TMDbMovieBatchScheduler.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryStep.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditStep.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverStep.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageStep.java
src/main/java/net/pointofviews/movie/batch/listener/MovieChunkListener.java
src/main/java/net/pointofviews/movie/batch/repository/JobExecutionRepository.java

- movie fetch 시 trending 바로 실행되도록 변경

feat: fetch 트리거 방식 변경

---

src/main/java/net/pointofviews/curation/dto/response/ReadAdminCurationMovieResponse.java
src/test/java/net/pointofviews/curation/service/CurationAdminServiceTest.java
src/test/java/net/pointofviews/curation/service/CurationMemberServiceImplTest.java

- 큐레이션 상세 반환 값 중 movieId를 id로 수정

refactor: 큐레이션 응답 값 네이밍 수정

---

src/main/java/net/pointofviews/movie/dto/response/MovieListResponse.java
src/main/java/net/pointofviews/movie/dto/response/MovieResponse.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/movie/service/MovieSearchService.java
src/main/java/net/pointofviews/movie/service/impl/MovieServiceImpl.java
src/test/java/net/pointofviews/movie/service/MovieServiceImplTest.java

refactor: 영화 전체 조회 응답 값 추가

---

src/main/java/net/pointofviews/common/repository/RedisRepository.java
src/main/java/net/pointofviews/common/repository/impl/StringRedisRepositoryImpl.java
src/main/java/net/pointofviews/common/service/RedisService.java
src/main/java/net/pointofviews/common/service/impl/StringRedisServiceImpl.java
src/main/java/net/pointofviews/movie/batch/dto/MovieContentsDto.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageProcessor.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageReader.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageWriter.java
src/main/java/net/pointofviews/movie/batch/trending/TMDbTrendingMovieReader.java
src/main/java/net/pointofviews/movie/batch/trending/TMDbTrendingMovieStep.java
src/main/java/net/pointofviews/movie/batch/trending/TMDbTrendingMovieWriter.java
src/main/java/net/pointofviews/movie/controller/MovieController.java
src/main/java/net/pointofviews/movie/controller/specification/MovieSpecification.java
src/main/java/net/pointofviews/movie/dto/response/MovieTrendingListResponse.java
src/main/java/net/pointofviews/movie/dto/response/MovieTrendingResponse.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/movie/service/MovieService.java
src/main/java/net/pointofviews/movie/service/impl/MovieServiceImpl.java

feat: 트렌딩 api를 이용한 영화 추천

---

src/main/java/net/pointofviews/review/dto/ReviewDetailsWithLikeCountDto.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java

refactor: 영화 상세조회 응답 컬럼명 변경

---

src/test/java/net/pointofviews/movie/service/MovieSearchServiceImplTest.java

refactor: 응답 테스트 수정

---

src/main/java/net/pointofviews/club/repository/ClubMoviesRepository.java
src/main/java/net/pointofviews/club/repository/MemberClubRepository.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java

feat: 리뷰 조회 관련 쿼리에 disabled 추가

---

src/main/java/net/pointofviews/club/controller/ClubController.java
src/main/java/net/pointofviews/club/controller/specification/ClubSpecification.java
src/main/java/net/pointofviews/club/exception/ClubException.java
src/main/java/net/pointofviews/club/service/impl/MemberClubServiceImpl.java
src/main/java/net/pointofviews/movie/batch/config/LimiterConfig.java
src/main/java/net/pointofviews/movie/batch/config/MovieBatchConfig.java
src/main/java/net/pointofviews/movie/batch/config/TaskExecutorConfig.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryProcessor.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryStep.java
src/main/java/net/pointofviews/movie/batch/country/TMDbMovieCountryWriter.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditReader.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditStep.java
src/main/java/net/pointofviews/movie/batch/credit/TMDbMovieCreditWriter.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverReader.java
src/main/java/net/pointofviews/movie/batch/discover/TMDbMovieDiscoverStep.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageProcessor.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageReader.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageStep.java
src/main/java/net/pointofviews/movie/batch/image/TMDbMovieImageWriter.java
src/main/java/net/pointofviews/movie/batch/release/TMDbMovieReleaseProcessor.java
src/main/java/net/pointofviews/movie/batch/repository/JobExecutionRepository.java
src/main/java/net/pointofviews/movie/batch/utils/ApiRateLimiter.java
src/main/java/net/pointofviews/movie/domain/Movie.java
src/main/java/net/pointofviews/movie/repository/MovieRepository.java

feat: 배치 방식 변경

---

src/main/java/net/pointofviews/review/repository/ReviewRepository.java
src/test/java/net/pointofviews/club/service/MemberClubServiceImplTest.java

feat: 리뷰 조회 조건 변경

---

src/main/java/net/pointofviews/movie/repository/MovieRepository.java

refactor: 영화 전체 조회 쿼리 WHERE 절 삭제

---

src/main/java/net/pointofviews/movie/dto/request/PutMovieRequest.java
src/main/java/net/pointofviews/movie/service/impl/MovieServiceImpl.java
src/main/java/net/pointofviews/review/repository/ReviewRepository.java

refactor: 영화 수정 시 요청 파라메터 이름 변경 genres -> genre

---

src/test/java/net/pointofviews/club/service/MemberClubServiceImplTest.java

test: 초대 응답 리디렉션 url 변경

---

src/main/java/net/pointofviews/premiere/controller/EntryController.java
src/main/java/net/pointofviews/premiere/controller/specification/EntrySpecification.java
src/main/java/net/pointofviews/premiere/service/EntryService.java
src/main/java/net/pointofviews/premiere/service/impl/EntryServiceImpl.java

test: 테스트를 위해 분산락을 적용하지 않은 응모 로직 추가

---

src/main/java/net/pointofviews/premiere/controller/EntryController.java
src/main/java/net/pointofviews/premiere/controller/specification/EntrySpecification.java

refactor: security 500 -> 403 반환으로 수정

---

README.md

chore: Create README.md
